export const exploracionesEndpoints = {
  muestras: "/api/exploraciones/muestras",
  muestrasTodas: "/api/exploraciones/muestras-todas",
  muestraById: (id: string) => `/api/exploraciones/muestras/${id}`,
  elementos: "/api/exploraciones/elementos",
  laboratorios: "/api/exploraciones/laboratorios",
  projects: "/api/mining-exploration/projects",
  projectById: (id: number) => `/api/mining-exploration/projects/${id}`,
  zones: "/api/mining-exploration/zones",
  zoneById: (id: number) => `/api/mining-exploration/zones/${id}`,
  drillholes: "/api/mining-exploration/drillholes",
  drillholeById: (id: number) => `/api/mining-exploration/drillholes/${id}`,
  intervals: "/api/mining-exploration/intervals",
  intervalById: (id: number) => `/api/mining-exploration/intervals/${id}`,
  assays: "/api/mining-exploration/assays",
  assayById: (id: number) => `/api/mining-exploration/assays/${id}`,
  lithologies: "/api/mining-exploration/lithologies",
  lithologyById: (id: number) => `/api/mining-exploration/lithologies/${id}`,
  qaqc: "/api/mining-exploration/qaqc",
  qaqcById: (id: number) => `/api/mining-exploration/qaqc/${id}`,
  resources: "/api/mining-exploration/resources",
  resourceById: (id: number) => `/api/mining-exploration/resources/${id}`,
  drillHoleSurveys: "/api/mining-exploration/drill-hole-surveys",
  drillHoleSurveyById: (id: number) => `/api/mining-exploration/drill-hole-surveys/${id}`,
  assayValues: "/api/mining-exploration/assay-values",
  assayValueById: (id: number) => `/api/mining-exploration/assay-values/${id}`,
  alterations: "/api/mining-exploration/alterations",
  alterationById: (id: number) => `/api/mining-exploration/alterations/${id}`,
  mineralizations: "/api/mining-exploration/mineralizations",
  mineralizationById: (id: number) => `/api/mining-exploration/mineralizations/${id}`,
  geologicalStructures: "/api/mining-exploration/geological-structures",
  geologicalStructureById: (id: number) => `/api/mining-exploration/geological-structures/${id}`,
  recoveries: "/api/mining-exploration/recoveries",
  recoveryById: (id: number) => `/api/mining-exploration/recoveries/${id}`,
  densities: "/api/mining-exploration/densities",
  densityById: (id: number) => `/api/mining-exploration/densities/${id}`,
  magneticSusceptibilities: "/api/mining-exploration/magnetic-susceptibilities",
  magneticSusceptibilityById: (id: number) =>
    `/api/mining-exploration/magnetic-susceptibilities/${id}`,
  significantIntercepts: "/api/mining-exploration/significant-intercepts",
  significantInterceptById: (id: number) => `/api/mining-exploration/significant-intercepts/${id}`,
  miningAreas: "/api/surface-exploration/mining-areas",
  miningAreaById: (id: string) => `/api/surface-exploration/mining-areas/${id}`,
  miningLevels: "/api/surface-exploration/mining-levels",
  miningLevelById: (id: string) => `/api/surface-exploration/mining-levels/${id}`,
  miningLabors: "/api/surface-exploration/mining-labors",
  miningLaborById: (id: string) => `/api/surface-exploration/mining-labors/${id}`,
  surfaceSamples: "/api/surface-exploration/samples",
  surfaceSamplesWithResults: "/api/surface-exploration/samples/with-results",
  surfaceSampleById: (id: string) => `/api/surface-exploration/samples/${id}`,
  surfaceLaboratories: "/api/surface-exploration/laboratories",
  surfaceLaboratoryById: (id: string) => `/api/surface-exploration/laboratories/${id}`,
  sampleLaboratories: "/api/surface-exploration/sample-laboratories",
  sampleLaboratoryById: (id: string) => `/api/surface-exploration/sample-laboratories/${id}`,
  surfaceElements: "/api/surface-exploration/elements",
  surfaceElementById: (id: string) => `/api/surface-exploration/elements/${id}`,
  sampleResults: "/api/surface-exploration/sample-results",
  sampleResultById: (id: string) => `/api/surface-exploration/sample-results/${id}`,
  sampleQaqc: "/api/surface-exploration/sample-qaqc",
  sampleQaqcById: (id: string) => `/api/surface-exploration/sample-qaqc/${id}`,
  interiorAreas: "/api/interior/areas",
  interiorAreaById: (id: string) => `/api/interior/areas/${id}`,
  interiorLevels: "/api/interior/levels",
  interiorLevelById: (id: string) => `/api/interior/levels/${id}`,
  interiorLabors: "/api/interior/labors",
  interiorLaborById: (id: string) => `/api/interior/labors/${id}`,
  interiorObjectives: "/api/interior/objectives",
  interiorObjectiveById: (id: string) => `/api/interior/objectives/${id}`,
  interiorLaboratories: "/api/interior/laboratories",
  interiorLaboratoryById: (id: string) => `/api/interior/laboratories/${id}`,
  interiorSamples: "/api/interior/samples",
  interiorSamplesWithResults: "/api/interior/samples/with-results",
  interiorSampleById: (id: string) => `/api/interior/samples/${id}`,
  interiorSampleWithResultsById: (id: string) => `/api/interior/samples/${id}/with-results`,
  interiorResults: "/api/interior/results",
  interiorResultById: (id: string) => `/api/interior/results/${id}`,
  surfaceSampleAreas: "/api/surface-sample/areas",
  surfaceSampleAreaById: (id: string) => `/api/surface-sample/areas/${id}`,
  surfaceSampleObjectives: "/api/surface-sample/objectives",
  surfaceSampleObjectiveById: (id: string) => `/api/surface-sample/objectives/${id}`,
  surfaceSampleLaboratories: "/api/surface-sample/laboratories",
  surfaceSampleLaboratoryById: (id: string) => `/api/surface-sample/laboratories/${id}`,
  surfaceProposalSamples: "/api/surface-sample/samples",
  surfaceProposalSamplesWithResults: "/api/surface-sample/samples/with-results",
  surfaceProposalSampleById: (id: string) => `/api/surface-sample/samples/${id}`,
  surfaceProposalSampleWithResultsById: (id: string) =>
    `/api/surface-sample/samples/${id}/with-results`,
  surfaceProposalResults: "/api/surface-sample/results",
  surfaceProposalResultById: (id: string) => `/api/surface-sample/results/${id}`,
  miningExcelValidate: "/api/imports/mining-excel/validate",
  miningExcelExecute: "/api/imports/mining-excel/execute"
} as const;
