// Módulo Sondajes (perforaciones en curso). Backend: /api/drilling
export const sondajesEndpoints = {
  summary: "/api/drilling/summary",
  contractors: "/api/drilling/contractors",
  contractorById: (id: string) => `/api/drilling/contractors/${id}`,
  rigs: "/api/drilling/rigs",
  rigById: (id: string) => `/api/drilling/rigs/${id}`,
  laboratories: "/api/drilling/laboratories",
  laboratoryById: (id: string) => `/api/drilling/laboratories/${id}`,
  campaigns: "/api/drilling/campaigns",
  campaignById: (id: string) => `/api/drilling/campaigns/${id}`,
  holes: "/api/drilling/holes",
  holeById: (id: string) => `/api/drilling/holes/${id}`,
  holesImport: "/api/drilling/holes/import",
  holeShiftReports: (holeId: string) => `/api/drilling/holes/${holeId}/shift-reports`,
  shiftReportById: (id: string) => `/api/drilling/shift-reports/${id}`,
  holeSurveys: (holeId: string) => `/api/drilling/holes/${holeId}/surveys`,
  surveyById: (id: string) => `/api/drilling/surveys/${id}`,
  holeRuns: (holeId: string) => `/api/drilling/holes/${holeId}/runs`,
  runById: (id: string) => `/api/drilling/runs/${id}`,
  holeCoreBoxes: (holeId: string) => `/api/drilling/holes/${holeId}/core-boxes`,
  coreBoxById: (id: string) => `/api/drilling/core-boxes/${id}`,
  holeLogIntervals: (holeId: string) => `/api/drilling/holes/${holeId}/log-intervals`,
  logIntervalById: (id: string) => `/api/drilling/log-intervals/${id}`,
  holeSamples: (holeId: string) => `/api/drilling/holes/${holeId}/samples`,
  samples: "/api/drilling/samples",
  sampleById: (id: string) => `/api/drilling/samples/${id}`,
  sampleResults: (sampleId: string) => `/api/drilling/samples/${sampleId}/results`,
  resultById: (id: string) => `/api/drilling/results/${id}`,
  dispatches: "/api/drilling/dispatches",
  dispatchById: (id: string) => `/api/drilling/dispatches/${id}`
} as const;
